### ISSUE TITLE
2_12 error?

### ISSUE THREAD

**Issue by ajlowndes** [jaipandya/SublimeTutor#18] opened 2016-06-13 07:48 UTC
On my macbook air w/ SublimeText 3114, CMD+/ just comments the line. If I press CMD+/ 4 times on that third line in the html code, I end up with:

   --> --> -->

**Comment by jaipandya** [comment] 2016-06-13 08:01
Closing this one as it is a duplicate of https://github.com/jaipandya/SublimeTutor/issues/19

**Closed as completed by jaipandya** 2016-06-13 08:01 UTC
